name: Update TryHackMe Badge

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update badge
        uses: actions/setup-node@v3
        with:
          node-version: 16
        env:
          THM_BADGE_URL: "https://tryhackme-badges.vercel.app/api?username=erockdu4" # Correct badge URL
        run: |
          const fs = require('fs').promises;
          const fetch = require('node-fetch');

          async function updateBadge() {
            const response = await fetch(process.env.THM_BADGE_URL);
            if (!response.ok) {
              throw new Error(`Failed to fetch badge: ${response.status} ${response.statusText}`);
            }
            const arrayBuffer = await response.arrayBuffer();
            const buffer = Buffer.from(arrayBuffer);
            await fs.writeFile('assets/tryhackme-badge.svg', buffer); // Write to the correct path
          }

          updateBadge().catch(error => {
            console.error(error);
            process.exit(1);
          });

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update TryHackMe badge"
          file_pattern: assets/tryhackme-badge.svg # Correct file path
